### ISSUE TITLE
CUDA support example

### ISSUE THREAD

**Issue by coen1111** [mohamed82008/TopOpt.jl#21]
In the code several references to GPU/CUDA support can be found. Could an example/turtorial how to get this working be an idea?

**Comment by mohamed82008** [comment]
This hasn't been functional for a while. I had to disable it while we were implementing truss optimization because trusses were more important. The CUDA implementation can also be improved significantly. Are you interested in using or developing GPU-accelerated topopt algorithms? If the latter, we can probably chat.
